language: node_js
node_js:
  - "6"

notifications:
  email:
    on_success: never
    on_failure: never

after_script:
  - npm install codecov
  - npm run test-travis
  - ./node_modules/.bin/codecov

# safelist
branches:
  only:
  - master
  - v0.1.1/master
