language: node_js
node_js:
  - "6"

notifications:
  email:
    on_success: never
    on_failure: never

after_script:
  - npm install codecov
  - npm install istanbul
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha ./test/ 
  - ./node_modules/.bin/codecov

# safelist
branches:
  only:
  - master
  - v0.1.0/master
